version: '3.8'

services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 81:81
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      - mongo  

  mongo:
    image: mongo

  logging_backend:
    image: ubuntu:latest
    volumes:
      - ./logs/backend:/logs
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SERVICE_NAME: backend
      LOG_FILE: /logs/backend.log
      BACKEND_PORT: 9003
    ports:
      - "9003:9003"
    command: /bin/bash -c "apt update && apt install -y docker-compose && /scripts/logging.sh $SERVICE_NAME $LOG_FILE $BACKEND_PORT"

  logging_web:
    image: ubuntu:latest
    volumes:
      - ./logs/web:/logs
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SERVICE_NAME: web
      LOG_FILE: /logs/web.log
      WEB_PORT: 9002
    ports:
      - "9002:9002"
    command: /bin/bash -c "apt update && apt install -y docker-compose && /scripts/logging.sh $SERVICE_NAME $LOG_FILE $WEB_PORT"
